name: CI
'on':
  push:
    branches:
      - main
  pull_request: null
jobs:
  shellcheck:
    uses: ./.github/workflows/ci_shellcheck.yml
  ubuntu_verify_repo:
    uses: ./.github/workflows/ci_ubuntu_verify_repo.yml
  ubuntu_verify_installation:
    uses: ./.github/workflows/ci_ubuntu_verify_installation.yml
  ubuntu_verify_protected_python:
    uses: ./.github/workflows/ci_ubuntu_verify_protected_python.yml
