name: CI run shellcheck on bash script
'on':
  workflow_call: null
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
